# Generated by Django 5.0.4 on 2024-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albom',
            old_name='coategory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='albom',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
