# Generated by Django 5.0.4 on 2024-04-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_coategory_albom_category_albom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
