# Generated by Django 5.0.4 on 2024-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='category',
            field=models.CharField(choices=[('all', 'Все'), ('voyge', 'Путишествия'), ('famaly', 'Семья'), ('party', 'Мероприятия'), ('birthday', 'Дни рождания')], default='birthday', max_length=255),
        ),
    ]
