# Generated by Django 5.0.4 on 2024-04-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('coategory', models.CharField(choices=[('voyge', 'Путишествия'), ('famaly', 'Семья'), ('party', 'Мероприятия'), ('birthday', 'Дни рождания'), ('all', 'Все')], default='all', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.albom')),
            ],
        ),
    ]
