# Generated by Django 5.0.4 on 2024-04-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albom',
        ),
        migrations.DeleteModel(
            name='Albom',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
